CREATE TABLE LibraryBook(bookID CHAR(100), 
isbn 		CHAR(13) NOT NULL,
branchNum 	CHAR(100) NOT NULL,
status		CHAR(100) NOT NULL,
PRIMARY KEY (bookID), 
FOREIGN KEY (isbn) REFERENCES Book(isbn)
ON UPDATE CASCADE
ON DELETE CASCADE, 
FOREIGN KEY (branchNum) REFERENCES LibraryBranch(branchNum)
ON UPDATE CASCADE
ON DELETE NO ACTION
);
